apiVersion: v1
kind: Service
metadata:
  name: weave-frontend
  namespace: weave
spec:
  selector:
    app: weave-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: weave-backend
  namespace: weave
spec:
  selector:
    app: weave-backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: weave-ws-relayer
  namespace: weave
spec:
  selector:
    app: weave-ws-relayer
  ports:
    - name: websocket
      protocol: TCP
      port: 80
      targetPort: 9093
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: weave
spec:
  selector:
    app: redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
